const DirectoryTypes = {
  DIRECTORY_FETCH_START: 'DIRECTORY_FETCH_START',
  DIRECTORY_FETCH_SUCCESS: 'DIRECTORY_FETCH_SUCCESS',
  DIRECTORY_FETCH_FAILURE: 'DIRECTORY_FETCH_FAILURE',
};

export default DirectoryTypes;
