const CollectionTypes = {
  FETCH_COLLECTION_START: 'FECTH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILED: 'FETCH_COLLECTION_FAILED',
};

export default CollectionTypes;
